# ==== Config file for running the 10x Cell Ranger pipeline ====================


# Path to the fastq directory, multiple directories can be given.
RAW_DATA:
    - "data/211230_novogene"
    - "data/220128_A00405_0521_AHH7JVDSX3"
    - "data/220311_A00405_0541_AHCMMHDSX3"

# Path to the output directory.
RESULTS:
    "results/2022-03-11"

# Sample names for gene expression fastqs. If the same libraries were
# sequenced multiple times, just include all the fastq directories in the
# RAW_DATA list and make sure the fastqs from all runs begin with the
# sample name. If gene expression fastqs are not being processed, leave
# this blank.
RNA_SAMPLES:
    - "BT_GEX_1"
    - "BT_GEX_2"
    - "BT_GEX_3"
    - "BT_GEX_4"
    - "BT_GEX_5"
    - "BT_GEX_6"
    - "BT_GEX_7"
    - "BT_GEX_8"

# Sample groups that should be used with cellranger aggr. Include the gene
# expression names separated by commas for samples that should be
# aggregated together. If only ADT fastqs are being processed, list the
# ADT names. Include multiple entries if multiple groups of samples are
# being aggregated. Leave blank to skip this step.
GROUPS:


# Path to the Cell Ranger genome reference.
GENOME:
    "/beevol/home/rbilab/ref/cellranger/mouse/refdata-gex-mm10-2020-A"

# Sample names for CITE-seq and cell hashing fastqs. If both methods were
# used, include both names separated by a comma. CITE-seq and cell hashing
# fastqs will be combined for each sample before running Cell Ranger. If 
# the libraries were sequenced multiple times, just make sure the fastqs 
# from all runs begin with the sample name. If CITE-seq or cell hashing 
# was not performed, leave this blank.
ADT_SAMPLES:
    - "BT_ADT_1"
    - "BT_ADT_2"
    - "BT_ADT_3"
    - "BT_ADT_4"
    - "BT_ADT_5"
    - "BT_ADT_6"
    - "BT_ADT_7"
    - "BT_ADT_8"

# Path to the antibody reference table used to extract the antibody name 
# and barcode. If CITE-seq or cell hashing was not performed, leave this 
# blank.
ADT_REF:
    "ref/antibodies.csv"

# List the TotalSeq catalog numbers for all antibodies used in the
# experiment. If CITE-seq or cell hashing was not performed, leave this
# blank.
ANTIBODIES:


# Sample names for VDJ fastqs. Follow the same parameters required for gene
# expression fastqs. If VDJ sequencing was not performed, leave this blank.
VDJ_SAMPLES:


# Path to the Cell Ranger VDJ reference. If VDJ sequencing was not performed,
# leave this blank.
VDJ_REF:


# Maximum number of jobs per sample that can be submitted by Cell Ranger
# at a time.
MAX_JOBS:
    24

# Path to an LSF template, this is optional.
LSF_TEMPLATE:
    "src/lsf.template"

# Chemistry to use for cellranger count. If this field is omitted from the
# config or left blank, 'auto' is used.
CHEM:



