---
title: "GeoMx"
author: "Ryan Sheridan"
date: "2024-03-13"
output: html_document
params:
  template_dir:  "src"                                                     # template Rmarkdowns
  so_dir:        "~/Dropbox/Ryan/Projects/antigen-exchange/results/sobjs"  # Seurat objects
  mod_dir:       "~/Dropbox/Ryan/Projects/antigen-exchange/results/models/2023-11-01" # ML models
  geomx_dir:     "results/geomx"
  chikv_dir:     "~/Dropbox/Ryan/Projects/morrison-lnsc/results/sobjs"     # CHIKV objects
  ref_dir:       "ref"                                                     # clustifyr references
  sample_info:   "sample_info.xlsx"
  res_dir:                                                
    value:
      exp-0: "~/Projects/antigen-tracking/results"
      exp-1: "~/Projects/tamburini-antigen-tracking/results/2022-03-11"
      exp-2: "~/Projects/tamburini-antigen-tracking/results/2022-10-28"
editor_options: 
  chunk_output_type: inline
---

```{r "setup", include = FALSE}
# Default chunk options
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo    = FALSE,
  dpi     = 300
)

# Increase memory for loading image
options(java.parameters = "-Xmx12000m")

knitr::knit(here::here(params$template_dir, "setup.Rmd"), "")
knitr::knit(here::here(params$template_dir, "setup-geomx.Rmd"), "")

rm(lec_so, dc_so)

geomx_dat <- geomx %>%
  pData() %>%
  as_tibble(rownames = "dcc")

# Mouse key
geo_m_key <- c(
  `3wk`     = "day 21",
  `6wk`     = "day 42",
  `6wk-3wk` = "dual",
  naive     = "naive"
)
```

## Extended figures

The sample identity is shown below for each slide.

```{r "all geomx samples", fig.width = 10, fig.height = 8}
plot_geomx_image <- function(obj_in, color, clrs = NULL, labs = waiver(),
                             legend_values = names(labs) %||% names(clrs),
                             ttl = NULL) {
  
  res <- obj_in %>%
    plotSpatialOverlay(
      colorBy          = color,
      scaleBar         = TRUE,
      corner           = "bottomleft",
      textDistance     = 1.5,
      scaleBarLineSize = 0.5,
      scaleBarFontSize = 8 / .pt
    ) +
    ggtitle(ttl) +
    theme(
      plot.margin  = margin(r = 20),
      plot.title   = element_text(hjust = 0.5, size = ttl_pt2 * 1.5),
      legend.title = element_blank(),
      legend.text  = element_text(size = ttl_pt1)
    )
  
  if (!is.null(legend_values)) {
    all_sams_df <- tibble(x = 1, y = 1, colorBy = legend_values)
    
    res <- res +
      geom_blank(aes(x, y, fill = colorBy), data = all_sams_df)
  }
  
  if (!is.null(clrs)) {
    if (is.numeric(obj_in@plottingFactors[[color]])) {
      res <- res +
        scale_fill_gradientn(colours = clrs)
    } else {
      res <- res +
        scale_fill_manual(values = clrs, labels = labs)
    }
  }
  
  res
}

geomx_imgs %>%
  imap(~ {
    .x %>%
      plot_geomx_image(
        color = "Sample",
        clrs  = geo_m_clrs,
        labs  = geo_m_key,
        ttl   = .y
      )
  }) %>%
  wrap_plots(
    guides = "collect",
    nrow = 1
  ) &
  theme(legend.position = "bottom")
```

Region labels are shown below for each slide.

```{r "all geomx regions", fig.width = 10, fig.height = 8}
geomx_imgs %>%
  imap(~ {
    .x %>%
      plot_geomx_image(
        color = "Region",
        clrs  = reg_clrs,
        ttl   = .y
      )
  }) %>%
  wrap_plots(
    guides = "collect",
    nrow = 1
  ) &
  theme(legend.position = "bottom")
```

Segment labels are shown below for each slide.

```{r "all geomx segments", fig.width = 10, fig.height = 8}
geomx_imgs %>%
  imap(~ {
    .x %>%
      plot_geomx_image(
        color = "Segment",
        clrs  = seg_clrs,
        ttl   = .y
      )
  }) %>%
  wrap_plots(
    guides = "collect",
    nrow = 1
  ) &
  theme(legend.position = "bottom")
```

The Ag signal is shown below for each region.

```{r "all geomx Ag-score", fig.width = 10, fig.height = 8}
geomx_imgs %>%
  imap(~ {
    .x %>%
      plot_geomx_image(
        color = "Ag-score",
        clrs  = c("white", "#D7301F", "#D7301F"),
        ttl   = .y
      ) +
      guides(fill = guide_colorbar(ticks = FALSE))
  }) %>%
  wrap_plots(nrow = 1) &
  theme(
    legend.position   = "bottom",
    legend.key.width  = unit(40, "pt"),
    legend.key.height = unit(7, "pt"),
    legend.text       = element_text(size = 8),
    legend.title      = element_text(size = txt_pt1)
  )
```



```{r "ova boxplots", eval = FALSE}
# Plot colors
seg_clrs <- c(medulla = "#D7301F", sinus = "#56B4E9", cortex = "#F0E442")

# Ova-3wk signal in each region for Lyve1 vs CD11C segments
clmn <- "Ag_score"
clmn <- "Ag_6wk_score"
clmn <- "Ag_3wk_score"

geomx_dat %>%
  filter(sample %in% c("3wk", "6wk-3wk"), Segment %in% c("Lyve1", "CD11C")) %>%
  
  ggplot(aes(region_3, !!sym(clmn), fill = region_3, color = region_2)) +
  geom_boxplot(key_glyph = draw_key_point, color = "black", alpha = 1) +
  facet_grid(~ Segment, scales = "free_y") +
  scale_fill_manual(values = seg_clrs) +
  labs(y = "Ova signal") +
  base_theme +
  theme(
    aspect.ratio    = 2,
    legend.position = "none",
    axis.text.x     = element_text(angle = 45, hjust = 1),
    axis.title.x    = element_blank()
  )

# Scatter plot comparing Lyve1 and CD11C segments
# clmn <- "ova-6wk"
# clmn <- "ova-3wk"
clmn <- "Ag_score"

dat <- geomx_dat %>%
  filter(
    Segment %in% c("Lyve1", "CD11C"),
    sample != "naive"
  ) %>%
  dplyr::select(
    `ROI Coordinate X`, `ROI Coordinate Y`,
    region_3, Segment, sample,
    !!sym(clmn)
  ) %>%
  group_by(`ROI Coordinate X`, `ROI Coordinate Y`) %>%
  filter(all(c("Lyve1", "CD11C") %in% Segment)) %>%
  ungroup() %>%
  mutate(Segment = str_c(Segment, "+ Ova signal")) %>%
  pivot_wider(names_from = Segment, values_from = !!sym(clmn))

# Correlation
cor <- cor(dat$`CD11C+ Ova signal`, dat$`Lyve1+ Ova signal`, method = "spearman")
cor <- round(cor, digits = 2)
cor <- str_c("r = ", cor)

sct_clrs <- seg_clrs
sct_clrs["cortex"] <- "black"

dat %>%
  ggplot(aes(`Lyve1+ Ova signal`, `CD11C+ Ova signal`, color = region_3)) +
  geom_smooth(method = "lm", color = "black", alpha = 0.2, linewidth = 0.5, linetype = 2) +
  geom_point() +
  scale_color_manual(values = sct_clrs) +
  base_theme +
  theme(
    aspect.ratio = 1,
    legend.title = element_blank()
  )
```

```{r "EACH SEPARATE", eval = FALSE}
var <- "Region"

geomx_imgs[1] %>%
  map(~ {
    obj  <- .x
    sams <- obj@plottingFactors$Sample %>%
      as.character() %>%
      unique() %>%
      na.omit()

    sams %>%
      map(~ {
        ids <- obj@plottingFactors %>%
          dplyr::filter(Sample == .x) %>%
          rownames() %>%
          unique()
        
        img <- obj %>%
          cropSamples(
            sampleIDs = ids, sampsOnly = FALSE, buffer = 0.2
          )

        img %>%
          plotSpatialOverlay(
            colorBy      = var,
            scaleBar     = TRUE,
            corner       = "bottomleft",
            textDistance = 5
          ) +
          ggtitle(.x) +
          geomx_theme
      }) %>%
      plot_grid(
        plotlist = .,
        ncol = 1
      )
  })
```

```{r "CROPPED IMAGES", eval = FALSE}
# Crop image to show selected ROIs
rois <- c("=\"006\"", "=\"007\"", "=\"008\"", "=\"022\"")

sams <- annots %>%
  filter(
    roi %in% rois,
    segment %in% c("Lyve1", "CD11C")
  ) %>%
  pull(Sample_ID)

# img_cropped <- img %>%
#   cropSamples(sampleIDs = sams, sampsOnly = TRUE)
```

```{r, eval = FALSE}
# Plot cropped image
# fig_dir <- "~/Dropbox/Ryan/Documents/Hesselberth_lab/Meetings/2024-03-12_data_club"

geomx_theme <- theme(
  legend.position = "bottom",
  legend.text     = element_text(size = 24),
  legend.title    = element_blank()
)

# img_cropped %>%
#   plotSpatialOverlay(
#     colorBy      = "Segment",
#     scaleBar     = TRUE,
#     corner       = "bottomleft",
#     textDistance = 5
#   ) +
#   scale_fill_manual(values = unname(seg_clrs)) +
#   geomx_theme
# 
# ggsave(here(fig_dir, "geomx_img_fig_1.png"), dpi = 400)

img %>%
  plotSpatialOverlay(
    colorBy      = "Sample",
    scaleBar     = TRUE,
    corner       = "bottomleft",
    textDistance = 5
  ) +
  # scale_fill_manual(values = seg_clrs) +
  geomx_theme

ggsave(here(fig_dir, "geomx_img_fig_2.png"), dpi = 400)

img_cropped %>%
  plotSpatialOverlay(
    colorBy      = "Ova",
    scaleBar     = TRUE,
    corner       = "bottomleft",
    textDistance = 5
  ) +
  scale_fill_gradient2(
    low = "grey", high = "#D7301F", mid = "#F0E442",
    midpoint = 2500
  )

ggsave(here(fig_dir, "geomx_img_fig_3.png"), dpi = 400)
```



