
```{r "abe setup", include = FALSE}
# Chunk options
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE,
  comment = "",
  echo    = FALSE,
  dpi     = 600
)

create_sobjs <- !file.exists(here(params$abe_dir, "abe_lec_so.qs"))

# Check for saved predictions
# * compare modification times to make sure models have not been re-trained
predict_cells <- .check_mtime(
  upstream_file = here(params$mod_dir, "ag-high_best_models.qs"),
  new_file      = here(params$mod_dir, "ag-high_abe_preds.qs")
)

predict_cells <- predict_cells || TRAIN_MODELS
```

```{r "abe functions"}
# Predict Ag-competent cells for data from Abe et al.
# * this must be done separately for each LEC subset
get_abe_preds <- function(so_in, mm_feats, hu_feats, predict_fn) {
  
  # Format data for predictions
  # * LEC1 == cLECs
  # * Calculate mean expression for mouse genes with multiple human homologs
  # * rename columns with mouse gene names
  # * add NAs for missing genes
  # * need to adjust gene names to remove "-" and add an "x" for genes starting with
  #   a number
  abe_dat <- so_in %>%
    .prepare_ml_data(feats = names(hu_feats), class_clmn = NULL)
  
  # Match mouse gene names
  abe_dat <- abe_dat %>%
    rownames_to_column(".cell_id") %>%
    pivot_longer(-.cell_id) %>%
    mutate(name_mm = hu_feats[as.character(name)]) %>%
    group_by(.cell_id, name_mm) %>%
    summarize(value = mean(value), .groups = "drop") %>%
    pivot_wider(names_from = name_mm) %>%
    column_to_rownames(".cell_id")
  
  # Add NAs for missing genes
  missing_feats <- mm_feats[!mm_feats %in% hu_feats]
  
  cli_alert_info(
    "{length(missing_feats)} / {length(mm_feats)}
     ({round({length(missing_feats)/length(mm_feats)}, 2)*100}%) missing"
  )
  
  abe_dat[, missing_feats] <- as.numeric(NA)
  
  # Predict Ag-competent cLECs
  pred <- predict_fn(as.h2o(abe_dat)) %>%
    pull(adj_pred) %>%
    factor(levels = ag_lvls)
  
  # Format final output
  res <- abe_dat %>%
    mutate(pred = pred) %>%
    select(pred)
  
  res
}
```

```{r "abe theme"}
abe_clrs <- c(
  MFLN = "#00B7A7",
  FL   = "#A40000"
)
```

```{r "abe process data", eval = create_sobjs}
# Load matrices
data_dir <- here("data/abe")
meta     <- read_tsv(here(data_dir, "metadata/sample_file.tsv"))

# For some reason there are duplicate files with the same name/MD5
# remove these duplicates
meta <- meta %>%
  mutate(
    md5 = map_chr(file_accession_id, ~ {
      md5 <- dir(here(data_dir, .x), pattern = ".md5$", full.names = TRUE)
      
      readLines(md5, warn = FALSE)
    }),
    duplicated = duplicated(md5)
  ) %>%
  filter(!duplicated)

# Create separate directory for each sample with symlinks
ega_dirs <- meta$file_accession_id

sams <- c()

ega_dirs %>%
  walk(~ {
    d <- file.path(data_dir, .x)
    
    file <- dir(d, pattern = ".gz$", full.names = TRUE)
    
    file_prfx <- str_extract(basename(file), "^[A-Z0-9_]+")
    file_base <- str_remove(basename(file), file_prfx)
    
    dir_nm <- file.path(data_dir, str_remove(file_prfx, "_$"))
    
    if (!dir.exists(dir_nm)) dir.create(dir_nm)
    
    file.symlink(file, file.path(dir_nm, file_base))
    
    if (!dir_nm %in% sams) sams <<- c(sams, dir_nm)
  })

names(sams) <- basename(sams)

# Create Seurat objects
abe_so <- sams %>%
  imap(~ {
    .x %>%
      Read10X() %>%
      CreateSeuratObject(project = .y) %>%
      mutate_meta(mutate, sample = .y)
  })

# Merge objects
abe_so <- merge(abe_so[[1]], abe_so[-1], add.cell.ids = names(abe_so))

abe_so <- abe_so %>%
  PercentageFeatureSet(pattern = "^MT-", col.name = "pct_mito") %>%
  subset(
    nFeature_RNA   < 5000 &
      nFeature_RNA > 250 &
      pct_mito     < 20
  ) %>%
  mutate_meta(
    mutate,
    tissue = str_extract(orig.ident, "^[A-Z]+")
  )

# Integrate samples
abe_so <- abe_so %>%
  norm_sobj(scale_data = FALSE) %>%
  integrate_sobjs(
    group_vars  = "orig.ident",
    dims        = 1:40,
    umap.method = "umap-learn"
  )
```

```{r "abe cell types", eval = create_sobjs}
# Annotate cell types
clst_clmn <- "RNA_snn_res.5"

abe_so <- abe_so %>%
  mutate_meta(mutate, cell_type = "other CD45-") %>%
  classify_markers(
    feats      = "PTPRC",
    filt       = PTPRC >= 0.4,
    clst_col   = clst_clmn,
    type_label = "other CD45+",
    type_col   = "cell_type"
  ) %>%
  classify_markers(
    feats      = c("cell_type", "PROX1", "PECAM1"),
    filt       = cell_type == "other CD45-" & PROX1 > 0.75 & PECAM1 > 1,
    clst_col   = clst_clmn,
    type_label = "LEC",
    type_col   = "cell_type"
  ) %>%
  classify_markers(
    feats      = c("cell_type", "JAM2", "PECAM1"),
    filt       = cell_type == "other CD45-" & JAM2 > 0.75 & PECAM1 > 1,
    clst_col   = clst_clmn,
    type_label = "BEC",
    type_col   = "cell_type"
  ) %>% 
  classify_markers(
    feats      = c("cell_type", "CR2"),
    filt       = cell_type == "other CD45-" & CR2 > 1,
    clst_col   = clst_clmn,
    type_label = "FDC",
    type_col   = "cell_type"
  )

save_objs(abe_so, ob_dir = params$abe_dir)
```

```{r "abe lec types", eval = create_sobjs, include = FALSE}
# Process LEC object
abe_lec_so <- abe_so %>%
  subset(cell_type == "LEC")

rm(abe_so)
gc()

abe_lec_so <- abe_lec_so %>%
  integrate_sobjs(
    group_vars  = "orig.ident",
    dims        = 1:40,
    umap.method = "umap-learn"
  )

# Annotate LEC subsets
abe_lec_so <- abe_lec_so %>%
  mutate_meta(dplyr::select, -any_of(c("type", "r", "UMAP_1", "UMAP_2"))) %>%
  clustify(
    ref_mat     = ref_LEC,
    cluster_col = "RNA_snn_res.3"
  )

# Adjust LEC labels
# * based on fig 3E from Abe et al.
typ_key <- c(
  LEC1 = "cLEC",
  LEC2 = "fLEC",
  LEC3 = "Collecting",
  LEC4 = "Ptx3_LEC",
  LEC5 = "Valve",
  LEC6 = "Marco_LEC"
)

abe_lec_so <- abe_lec_so %>%
  mutate_meta(
    mutate,
    subtype = typ_key[type],
    subtype = replace_na(subtype, "unassigned")
  )

# Save object
save_objs(abe_lec_so, ob_dir = params$abe_dir)
```

```{r "abe load object"}
abe_lec_so <- load_obj(here(params$abe_dir, "abe_lec_so.qs"))
```

```{r "abe load homologs", eval = predict_cells}
# Get human/mouse homologs
# * get server error when using default host
host   <- "https://dec2021.archive.ensembl.org"
biomrt <- "ensembl"
h_mart <- useEnsembl(biomrt, dataset = "hsapiens_gene_ensembl",  host = host)
m_mart <- useEnsembl(biomrt, dataset = "mmusculus_gene_ensembl", host = host)

hlogs <- getLDS(
  filters     = "external_gene_name",
  values      = ML_FEATS,
  attributes  = c("external_gene_name", "entrezgene_id"),
  attributesL = c("external_gene_name", "entrezgene_id"),
  mart        = m_mart,
  martL       = h_mart
)

# Format columns
# mouse columns end in '.1'
hlogs <- hlogs %>%
  rename_with(.cols = matches("[^1]$"),   ~ str_c(.x, "_mm")) %>%
  rename_with(.cols = ends_with(".1"),       ~ str_replace(.x, ".1$", "_hs")) %>%
  rename_with(.cols = matches("^Gene.name"), ~ str_replace(.x, "^[^_]+", "gene")) %>%
  rename_with(.cols = matches("^NCBI"),      ~ str_replace(.x, "^[^_]+", "entrez")) %>%
  as_tibble() %>%
  mutate(across(everything(), ~ str_replace(.x, "^$", as.character(NA)))) %>%
  distinct(gene_mm, gene_hs, entrez_hs)

hlogs %>%
  write_tsv(here(params$ref_dir, "hlogs.tsv.gz"))

# Identify human homologs
# * exclude duplicated mouse and human genes
hu_feats <- hlogs %>%
  filter(
    gene_mm %in% ML_FEATS,
    gene_hs %in% rownames(abe_lec_so)
  ) %>%
  filter(
    !duplicated(gene_mm),
    !duplicated(gene_hs)
  )

hu_feats <- set_names(hu_feats$gene_mm, hu_feats$gene_hs)

# Save gene modules
# * only use modules from the best model
module_key <- set_names(names(hu_feats), unname(hu_feats))

hu_modules <- MODULE_FEATS[[1]][rf_typs] %>%
  imap(~ {
    mods <- .x %>%
      map(~ as.character(na.omit(unname(module_key[.x]))))
    
    names(mods) <- str_c(.y, "_", names(.x))
    
    mods
  }) %>%
  flatten()

hu_modules %>%
  qsave(here(params$mod_dir, "ag-high_abe_features.qs"))
```

```{r "abe predict Ag-competent", eval = predict_cells}
# Predicate Ag-competent cells
# * predictions are made only for the specific cell type
abe_preds <- BEST_MLS %>%
  split(.$model_name) %>%
  map(~ {
    .x %>%
      pmap_dfr(~ {
        args <- list(...)
        
        get_abe_preds(
          so_in      = subset(abe_lec_so, subtype == args$subtype),
          mm_feats   = ML_FEATS,
          hu_feats   = hu_feats,
          predict_fn = args$predict_fn
        )
      })
  })

# Save predictions
abe_preds %>%
  qsave(here(params$mod_dir, "ag-high_abe_preds.qs"))
```

```{r "abe add predictions"}
# Load predictions
hu_modules <- qread(here(params$mod_dir, "ag-high_abe_features.qs"))

abe_preds <- qread(here(params$mod_dir, "ag-high_abe_preds.qs"))

# Add predictions to object
abe_preds %>%
  iwalk(~ {
    abe_lec_so <<- abe_lec_so %>%
      AddMetaData(.x, col.name = str_c("ml_", colnames(.x), "_", .y))
  })

abe_lec_so <- abe_lec_so %>%
  mutate_meta(~ {
    .x %>%
      mutate(
        across(matches("^ml_pred_[0-9]+"), ~ {
          .x %>%
            dplyr::recode(high = "Ag-competent", low = "Ag-low")
        }, .names = "{.col}_grp")
      )
  })

# Add module scores
# * only add scores for top model
module_nms <- set_names(
  str_c(names(hu_modules), seq_along(hu_modules)),
  names(hu_modules)
)

abe_lec_so <- abe_lec_so %>%
  mutate_meta(dplyr::select, -any_of(matches("_(low|high)"))) %>%
  AddModuleScore(features = hu_modules, name = names(hu_modules)) %>%
  mutate_meta(rename, !!!module_nms)
```
