
```{r "chikv setup"}
# Check for saved predictions
# * compare modification times to make sure models have not been re-trained
# * will return TRUE if new_file is missing or is older than upstream_file
predict_cells <- .check_mtime(
  upstream_file = here(params$mod_dir, "ag-high_best_models.qs"),
  new_file      = here(params$mod_dir, "ag-high_chikv_preds.qs")
)

predict_cells <- predict_cells || TRAIN_MODELS
```

```{r "chikv theme"}
# CHIKV theme
chikv_clrs <- c(
  `Ag-low`       = "#56B4E9",
  `Ag-competent` = "#D7301F",
  other          = "white"
)

treat_clrs <- set_names(chikv_clrs[1:2], c("mock", "CHIKV"))

chikv_u_theme <- umap_theme_2 +
  theme(aspect.ratio = 0.7)
```

```{r "chikv load data"}
# Load CHIKV data
chikv_so <- qread(here(params$chikv_dir, "so_lec.qs"))

chikv_so <- chikv_so %>%
  subset(tm == "24hpi") %>%
  AddMetaData(FetchData(., c("hUMAP_1", "hUMAP_2"))) %>%
  DietSeurat(assays = "RNA", counts = FALSE)

chikv_clmns <- c(
  "orig.ident", "rep", "treatment", "tm",
  CHIKV_TYPE_CLMN,
  "UMAP_1", "UMAP_2"
)
```

```{r "chikv predict Ag-competent", eval = predict_cells}
# Predict using models for each LEC subset
chikv_preds <- BEST_MLS %>%
  split(.$model_name) %>%
  map(~ {
    .x %>%
      pmap_dfr(~ {
        args <- list(...)
        
        cells <- chikv_so@meta.data %>%
          filter(!!sym(CHIKV_TYPE_CLMN) == args$subtype) %>%
          rownames()
        
        dat <- chikv_so %>%
          subset(cells = cells)
        
        res <- dat %>%
          .predict_ml(
            predict_fn = args$predict_fn,
            class_clmn = NULL
          )
        
        res
      })
  })

# Save predictions
chikv_preds %>%
  qsave(here(params$mod_dir, "ag-high_chikv_preds.qs"))
```

```{r "chikv format data 1", include = FALSE}
# Load CHIKV predictions
chikv_preds <- qread(here(params$mod_dir, "ag-high_chikv_preds.qs"))

# Add Ag-competent predictions
chikv_preds %>%
  iwalk(~ {
    chikv_so <<- chikv_so %>%
      AddMetaData(.x, col.name = str_c("ml_", colnames(.x), "_", .y))
  })

chikv_so <- chikv_so %>%
  mutate_meta(~ {
    .x %>%
      mutate(
        across(matches("^ml_pred_[0-9]+"), ~ {
          .x %>%
            dplyr::recode(high = "Ag-competent", low = "Ag-low") %>%
            fct_relevel(rev(names(chikv_clrs)))
        }, .names = "{.col}_grp"),
        
        treatment = fct_relevel(treatment, c("mock", "CHIKV")),
        subtype   = !!sym(CHIKV_TYPE_CLMN)  # add subtype column to keep consistent
      )
  })

# Add module scores
# * only add modules for top prediction
CHIKV_FEATS <- MODULE_FEATS[[1]]

CHIKV_FEATS %>%
  iwalk(~ {
    clmn_nms <- str_c(.y, "_", names(.x))

    clmn_nms <- set_names(
      str_c(clmn_nms, seq_along(clmn_nms)),
      clmn_nms
    )

    chikv_so <<- chikv_so %>%
      AddModuleScore(
        features = .x,
        name     = names(clmn_nms)
      ) %>%
      mutate_meta(dplyr::rename, !!!syms(clmn_nms))
  })
```

```{r "chikv format data 2", include = FALSE}
# Data for plotting
# * cLEC Ag-high heatmap data, not all genes are in CHIKV object
# * only pull module features for top model
# * include top 75 genes for figures
CHIKV_FEATS <- CHIKV_FEATS[[rf_cell_type]]$high
CHIKV_FEATS <- CHIKV_FEATS[CHIKV_FEATS %in% rownames(chikv_so)]
CHIKV_FEATS <- head(CHIKV_FEATS, 70)

fetch_feats <- c(
  "treatment", "rep", "lec_subtype",
  colnames(chikv_so@meta.data),
  unique(c(CHIKV_FEATS, "Icam1", "Mrc1"))
) %>%
  unique()

CHIKV_DAT <- chikv_so %>%
  FetchData(fetch_feats) %>%
  as_tibble(rownames = ".cell_id")

# Add Icam1 groups
CHIKV_DAT <- CHIKV_DAT %>%
  mutate(
    is_LEC = !(!!sym(CHIKV_TYPE_CLMN) %in% c("BEC", "unassigned")),
    cut    = median(Icam1[is_LEC & Icam1 > 0]),
    icam_grp = case_when(
      Icam1 == 0   ~ "ICAM-lo",
      Icam1 < cut  ~ "ICAM-mid",
      Icam1 >= cut ~ "ICAM-hi"
    ),
    icam_grp = fct_relevel(icam_grp, c("ICAM-hi", "ICAM-mid", "ICAM-lo"))
  )
  
rm(chikv_so)
gc()
```
